[package]
name = "limbo"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
iced = { version = "0.13.1", features = ["tokio", "image", "svg"] }
iced_layershell = "0.13.6"
hyprland = "0.4.0-beta.2"
